### ISSUE TITLE
Добавить поле organization_id в CSV

### ISSUE THREAD

**Issue by gsk990** [opendataby/115#16]

**Comment by gsk990** [comment]
скрипт поправлен но выдаёт ошибку, дебажим

**Comment by abitrolly** [comment]
SNAFUed with https://github.com/opendataby/115/commit/2b42f566e05ca62d4a3b165606a82723d1971d54
```
7:37:27 PM: creating opendata-115-2018-02-01.csv
7:37:27 PM: Traceback (most recent call last):
7:37:27 PM:   File "003-parse.py", line 149, in <module>
7:37:27 PM:     json2csv(name, outname)
7:37:27 PM:   File "003-parse.py", line 137, in json2csv
7:37:27 PM:     writer.writerow(entry)
7:37:27 PM:   File "/usr/lib/python2.7/csv.py", line 152, in writerow
7:37:27 PM:     return self.writer.writerow(self._dict_to_list(rowdict))
7:37:27 PM:   File "/usr/lib/python2.7/csv.py", line 148, in _dict_to_list
7:37:27 PM:     + ", ".join([repr(x) for x in wrong_fields]))
7:37:27 PM: ValueError: dict contains fields not in fieldnames: 'organisation_id'
```
Need better error message.

**Comment by abitrolly** [comment]
Done.
